# Generated by Django 6.0.3 on 2026-06-07 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '検知キーワード',
                'verbose_name_plural': '検知キーワード',
                'ordering': ['-score', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='WatchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('source_type', models.CharField(choices=[('rss', 'RSS'), ('html', 'HTML')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '監視サイト',
                'verbose_name_plural': '監視サイト',
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DetectedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('is_alert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_items', to='signals.watchsource')),
            ],
            options={
                'verbose_name': '検知記事',
                'verbose_name_plural': '検知記事',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
