# Generated by Django 6.0.3 on 2026-06-07 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '監視商品',
                'verbose_name_plural': '監視商品',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='detecteditem',
            name='premium_probability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detecteditem',
            name='prevalue_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='detecteditem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_items', to='signals.trackedproduct'),
        ),
    ]
