# Generated by Django 6.0.3 on 2026-06-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_trackedproduct_detecteditem_premium_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detecteditem',
            name='external_signal_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='detecteditem',
            name='google_trend_growth_pct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detecteditem',
            name='google_trend_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detecteditem',
            name='social_buzz_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detecteditem',
            name='social_mentions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
