# Generated by Django 6.0.3 on 2026-03-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, help_text='ティッカー / 銘柄コード（例: 7203.T, AAPL）', max_length=32, unique=True)),
                ('name', models.CharField(help_text='銘柄名（例: トヨタ自動車, Apple Inc.）', max_length=255)),
                ('market', models.CharField(blank=True, help_text='市場区分（例: JP, US, TSE など。任意）', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='監視中かどうか')),
                ('memo', models.TextField(blank=True, help_text='メモ（任意）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '監視銘柄',
                'verbose_name_plural': '監視銘柄',
                'ordering': ['-updated_at', 'ticker'],
            },
        ),
    ]
