# Generated by Django 6.0.3 on 2026-03-13 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='日付（終値ベースの日付など）')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField(blank=True, help_text='出来高（任意）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(help_text='対象となる監視銘柄', on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stocks.watchstock')),
            ],
            options={
                'verbose_name': '日足株価',
                'verbose_name_plural': '日足株価',
                'ordering': ['-date', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_date')],
            },
        ),
    ]
