# Generated by Django 6.0.3 on 2026-03-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockpricedaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_date', models.DateField(help_text='シグナル日付（通常 latest_date）')),
                ('signal_type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell'), ('neutral', 'neutral')], max_length=16)),
                ('buy_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sell_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_bias', models.CharField(max_length=16)),
                ('score_strength', models.CharField(max_length=16)),
                ('signal_price', models.DecimalField(blank=True, decimal_places=4, help_text='シグナル生成時の価格（通常 latest_close）', max_digits=12, null=True)),
                ('latest_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ma25', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ma75', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('high_20', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('low_20', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('trend_short', models.CharField(blank=True, max_length=16, null=True)),
                ('trend_mid', models.CharField(blank=True, max_length=16, null=True)),
                ('trend_long', models.CharField(blank=True, max_length=16, null=True)),
                ('volume_trend', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(help_text='対象となる監視銘柄', on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='stocks.watchstock')),
            ],
            options={
                'ordering': ['-signal_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'signal_date'), name='unique_stock_signal_per_day')],
            },
        ),
    ]
