# Generated by Django 6.0.3 on 2026-03-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_tradingsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='technical_position',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='20日レンジ内での価格位置（0〜1）', max_digits=5, null=True),
        ),
    ]
