# Generated by Django 6.0.3 on 2026-03-13 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_tradingsignal_technical_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('eval_status', models.CharField(default='pending', max_length=16)),
                ('date_5d', models.DateField(blank=True, null=True)),
                ('close_5d', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('return_5d', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('success_5d', models.BooleanField(blank=True, null=True)),
                ('date_10d', models.DateField(blank=True, null=True)),
                ('close_10d', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('return_10d', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('success_10d', models.BooleanField(blank=True, null=True)),
                ('date_20d', models.DateField(blank=True, null=True)),
                ('close_20d', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('return_20d', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('success_20d', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='stocks.tradingsignal')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
