# Generated by Django 5.2.1 on 2026-03-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_scoreprofileproposal_applied_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scoreprofileproposal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signaloutcome',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockpricedaily',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='watchstock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ScoreProfileActivationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_profile_name_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('previous_profile_version_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('activated_profile_name_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('activated_profile_version_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('source_proposal_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('activation_reason', models.CharField(default='manual_activate', help_text='active 化の理由（例: manual_activate, apply_and_activate など）', max_length=50)),
                ('note', models.TextField(blank=True, default='', help_text='任意のメモ（運用理由など）')),
                ('activated_at', models.DateTimeField(auto_now_add=True, help_text='active 化を実行した日時')),
                ('activated_profile', models.ForeignKey(help_text='この履歴で active にした ScoreProfile', on_delete=django.db.models.deletion.CASCADE, related_name='activated_histories', to='stocks.scoreprofile')),
                ('previous_profile', models.ForeignKey(blank=True, help_text='切り替え前に active だった ScoreProfile（初回は NULL 可）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_histories', to='stocks.scoreprofile')),
                ('source_proposal', models.ForeignKey(blank=True, help_text='有効化した ScoreProfile の元になった proposal（特定できる場合のみ）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_histories', to='stocks.scoreprofileproposal')),
            ],
            options={
                'verbose_name': 'スコアプロファイル有効化履歴',
                'verbose_name_plural': 'スコアプロファイル有効化履歴',
                'ordering': ['-activated_at', '-id'],
            },
        ),
    ]
