# Generated by Django 6.0.3 on 2026-03-14 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_alter_scoreprofile_id_alter_scoreprofileproposal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scoreprofileactivationhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scoreprofileproposal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signaloutcome',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockpricedaily',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='watchstock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StockPrice5Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='5分足の始まりの日時（UTC またはローカル）')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(help_text='対象となる監視銘柄', on_delete=django.db.models.deletion.CASCADE, related_name='prices_5m', to='stocks.watchstock')),
            ],
            options={
                'verbose_name': '5分足株価',
                'verbose_name_plural': '5分足株価',
                'ordering': ['-datetime', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'datetime'), name='unique_stock_5m_datetime')],
            },
        ),
        migrations.CreateModel(
            name='StockPriceMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='月の代表日（例: 月末）')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(help_text='対象となる監視銘柄', on_delete=django.db.models.deletion.CASCADE, related_name='prices_monthly', to='stocks.watchstock')),
            ],
            options={
                'verbose_name': '月足株価',
                'verbose_name_plural': '月足株価',
                'ordering': ['-date', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_monthly_date')],
            },
        ),
    ]
