# Generated by Django 6.0.3 on 2026-03-14 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_stockprice_5m_monthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='週の代表日（例: 週末）')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(help_text='対象となる監視銘柄', on_delete=django.db.models.deletion.CASCADE, related_name='prices_weekly', to='stocks.watchstock')),
            ],
            options={
                'verbose_name': '週足株価',
                'verbose_name_plural': '週足株価',
                'ordering': ['-date', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_weekly_date')],
            },
        ),
    ]
