# Generated by Django 6.0.3 on 2026-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_stockprice_weekly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreprofile',
            name='version',
            field=models.CharField(blank=True, default='', help_text='バージョン識別子（未使用の場合は空）。説明で識別する想定。', max_length=32),
        ),
        migrations.AlterField(
            model_name='watchstock',
            name='is_active',
            field=models.BooleanField(default=True, help_text='有効かどうか（無効は監視対象外）'),
        ),
        migrations.AlterField(
            model_name='watchstock',
            name='ticker',
            field=models.CharField(db_index=True, help_text='銘柄コード（例: 7203.T, AAPL）', max_length=32, unique=True),
        ),
    ]
