# Generated by Django 6.0.3 on 2026-03-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_scoreprofile_version_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreprofile',
            name='trading_style',
            field=models.CharField(choices=[('long_term', '長期（スイング・ポジション）'), ('short_term', '短期（数日〜数週間）'), ('day_trade', 'デイトレ')], default='short_term', help_text='長期/短期/デイトレ。シグナル発報の時間軸・頻度の判断に使う。', max_length=16),
        ),
    ]
