# Generated by Django 6.0.3 on 2026-03-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_add_scoreprofile_trading_style'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradingsignal',
            name='unique_stock_signal_per_day',
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='signal_datetime',
            field=models.DateTimeField(blank=True, help_text='デイトレ等の intraday 発報時のみ設定。日足シグナルは null。', null=True),
        ),
        migrations.AddConstraint(
            model_name='tradingsignal',
            constraint=models.UniqueConstraint(fields=('stock', 'signal_date', 'signal_datetime'), name='unique_stock_signal_per_day_datetime'),
        ),
    ]
